ml.combust.mleap.xgboost.ops = [
  "ml.combust.mleap.xgboost.runtime.bundle.ops.XGBoostPredictorClassificationOp",
  "ml.combust.mleap.xgboost.runtime.bundle.ops.XGBoostPredictorRegressionOp"
]

ml.combust.mleap.registry.default.ops += "ml.combust.mleap.xgboost.ops"
