name: Release
on:
  push:
    branches: [master]
    tags: ["v*"]

jobs:
  publish-scala:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: sbt/setup-sbt@v1
      - run: make ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.GPG_SECRET_KEY }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  publish-python:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install twine wheel setuptools
      - run: make -C python upload
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}